folders:
  assets: "assets"

files:
  raw_output: "usb_pd_spec.jsonl"
  clean_output: "usb_pd_spec_clean.jsonl"
  default_pdf: "USB_PD_R3_2 V1.1 2024-10.pdf"
  
parser:
  doc_title: "USB Power Delivery Specification"
  
patterns:
  section_regex: "^\\d+(\\.\\d+)*$"
  section_title_regex: "^(\\d+(?:\\.\\d+)*)\\s+(.+)"