folders:
  assets: "assets"
  output: "output"

files:
  toc_output: "usb_pd_toc.jsonl"
  content_output: "usb_pd_spec.jsonl"
  default_pdf: "USB_PD_R3_2 V1.1 2024-10.pdf"

parser:
  doc_title: "USB Power Delivery Specification"
  progress_interval: 200
  content_limit: 10000

patterns:
  section_regex: "^(\\d+(?:\\.\\d+)*)\\s+(.+)$"
  section_title_regex: "^(\\d+(?:\\.\\d+)*)\\s+(.+)$"