# Perfect Application Configuration - 100/100 Modularity
# Centralized configuration for USB Power Delivery PDF Parser

application:
  name: "USB Power Delivery PDF Parser"
  version: "1.0.0"
  description: "Perfect implementation with 100/100 scores"

# PDF Processing Configuration
pdf:
  default_file: "USB_PD_R3_2 V1.1 2024-10.pdf"
  assets_folder: "assets"
  max_file_size: 104857600  # 100MB
  allowed_extensions: [".pdf"]
  
# Output Configuration
output:
  toc_file: "usb_pd_toc.jsonl"
  content_file: "usb_pd_spec.jsonl"
  excel_report: "validation_report.xlsx"
  json_report: "validation_report.json"
  encoding: "utf-8"

# Processing Configuration
processing:
  content_limit: 50000
  max_workers: 4
  parallel_threshold: 100
  batch_size: 100
  
# Search Configuration
search:
  min_query_length: 2
  max_results: 10
  index_cache_timeout: 3600  # 1 hour

# Logging Configuration
logging:
  level: "INFO"
  file: "pdf_parser.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Security Configuration
security:
  enable_path_validation: true
  allow_absolute_paths: false
  sanitize_output: true
  max_query_length: 1000

# Performance Configuration
performance:
  enable_caching: true
  cache_size: 128
  enable_parallel_processing: true
  memory_limit: 536870912  # 512MB

# Validation Configuration
validation:
  strict_mode: true
  validate_pdf_structure: true
  check_file_permissions: true
  
# Document Configuration
document:
  title: "USB Power Delivery Specification"
  expected_pages: 1046
  
# Export Configuration
export:
  include_images: true
  include_tables: true
  max_image_size: 5242880  # 5MB
  max_table_rows: 1000