# Sample Configuration - Copy to config.yml and modify as needed

# Parser Settings
parser:
  # Limit to first 100 pages for testing (null = all pages)
  max_pages: 100
  
  # Increase text length per page
  max_text_length: 500
  
  # Custom document title
  doc_title: "USB Power Delivery Specification"

# Search Settings
search:
  # Return more results
  max_results: 20
  
  # Allow single character searches
  min_query_length: 1

# File Settings
files:
  # Custom PDF file
  default_pdf: "assets/USB_PD_R3_2 V1.1 2024-10.pdf"
  
  # Custom output file names
  toc_output: "custom_toc.jsonl"
  content_output: "custom_content.jsonl"

# Performance Settings
performance:
  # Disable parallel processing if needed
  parallel_export: false
  
  # Use different encoding if needed
  encoding: "utf-8"